// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbdJeq5Csl8SPwHqDONLPKETO05M_0JQ',
    appId: '1:819892134196:web:21a7e73177c314083ac561',
    messagingSenderId: '819892134196',
    projectId: 'authproject-1a382',
    authDomain: 'authproject-1a382.firebaseapp.com',
    storageBucket: 'authproject-1a382.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcf9SO27WTD4h-Tqp-iRBfg0mRNm5838',
    appId: '1:819892134196:android:fc1916d2afb3eb773ac561',
    messagingSenderId: '819892134196',
    projectId: 'authproject-1a382',
    storageBucket: 'authproject-1a382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXyLaj62X82sKYhCtOc6hqAFlVC9PGcKo',
    appId: '1:819892134196:ios:8b8783e49a160c623ac561',
    messagingSenderId: '819892134196',
    projectId: 'authproject-1a382',
    storageBucket: 'authproject-1a382.appspot.com',
    iosClientId: '819892134196-7g459f6focsco6difmfdtvva534rqpd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXyLaj62X82sKYhCtOc6hqAFlVC9PGcKo',
    appId: '1:819892134196:ios:bb5a4bea36caef2c3ac561',
    messagingSenderId: '819892134196',
    projectId: 'authproject-1a382',
    storageBucket: 'authproject-1a382.appspot.com',
    iosClientId: '819892134196-2m79schp7l7dci9n14hjsblo46mgol18.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
